spring:
  config:
    import: "file:secrets.yaml"
  application:
    name: java-ecom
  h2:
    console:
      enabled: true
  main:
    banner-mode: OFF
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: off

project:
  image: images/

logging:
  level:
    root: WARN
    org.springframework: OFF
    org.hibernate.SQL: OFF
    springframework.security: OFF
    com.ecommerce.javaecom: OFF

